title: Erik Downes | Financial Mathematics
description: Erik's profile, aviation learning, mathematics modules and applied projects.
url: https://ronandownes.github.io
baseurl: /coop
markdown: kramdown
