title: Erik Downes | Financial Mathematics
description: Erik's profile, aviation learning, mathematics studies and portfolio work.
url: https://ronandownes.github.io
baseurl: /coop
markdown: kramdown
